:toc:

ifdef::env-github[]
:imagesdir: /src/main/adoc
endif::[]

= Web Electricity Router Board

== Description

This project is an Open Source / Open Hardware minimal approach to build a Web-accessible Electricity Router Board.

Board features:

- have REST API
- have Web Socket API
- capture Téléinfo (France Electricity provider serial consumption data)
- have switchable Main Ppower 230v relays (SSR or not) to force device such as Water heater
- have programmable fils pilotes (8+) to set orders onto electric heaters 
- (optional) have accurate temperature / humidity sensor

WARNING: Caution with 230v. Do not use high current.WARNING: Caution with 230v. Do not use high current.

The board uses HTTP/REST API as interface.
Additionaly, simple Web UI is implemented on top of the REST API.

In practice, the Web Relay is used to manage both:

- electric heaters with data wire named link:http://www.planete-domotique.com/blog/2012/01/05/piloter-un-radiateur-grace-a-son-fil-pilote/[fil pilote] which is 230v at very low current
- electric water heater

The overall devices are ochestrated through Node-Red monitoring and triggering relays or optocouplers.

NOTE: This project is part of a wider link:https://github.com/kalemena/ti-dhome[TiDhome Home Automation] project.

